---
sudo: required
language: python
cache: pip
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install:
  - pip install molecule docker
script:
  - molecule test -s centos
  - echo DOCKER && docker ps
  - molecule test -s ubuntu
  - echo DOCKER && docker ps
  - molecule test -s debian
  - echo DOCKER && docker ps
